//////////////////////////////
// 0 - Black Wolf Talisman //
////////////////////////////

COPY ~weidu_external/%MOD_FOLDER%/bam/ibwtalis.bam~ ~override~

COPY ~iwditempack/itm/bwtalis.itm~ ~override~
  SAY NAME1 @2
  SAY UNIDENTIFIED_DESC @3
  SAY NAME2 @4
  LPF ~GW_WRITE_EE_ITM_DESCRIPTIONS~ STR_VAR GW_desc_to_update = "@5" END
  
COPY_EXISTING ~wmart1.sto~ ~override~  // add item to Joluv shop

	LPF ADD_STORE_ITEM_EX
      STR_VAR item_name=~bwtalis~ flags=~identified~
    END
