/////////////////////////////////////////
// 3 - Kegsplitter of Shaengarne Ford //
///////////////////////////////////////

COPY ~weidu_external/%MOD_FOLDER%/bam/iax1hks.bam~ ~override~

COPY ~iwditempack/itm/xohfaxks.itm~ ~override~
  SAY NAME1 @20
  SAY UNIDENTIFIED_DESC @21
  SAY NAME2 @22
  LPF ~GW_WRITE_EE_ITM_DESCRIPTIONS~ STR_VAR GW_desc_to_update = "@23" END
  WRITE_ASCII 0x58 ~CAX1H04~ (8) // Description image
  
COPY_EXISTING ~wmart1.sto~ ~override~  // add item to Joluv shop

	LPF ADD_STORE_ITEM_EX
      STR_VAR item_name=~xohfaxks~ flags=~identified~
    END
	