///////////////////////////////////////////
// 10 - Binding Sash of the Black Raven //
/////////////////////////////////////////

COPY ~weidu_external/%MOD_FOLDER%/bam/ibeltsb.bam~ ~override~

COPY ~iwditempack/itm/xohfbtsb.itm~ ~override~
  SAY NAME1 @57
  SAY UNIDENTIFIED_DESC @58
  SAY NAME2 @59
  LPF ~GW_WRITE_EE_ITM_DESCRIPTIONS~ STR_VAR GW_desc_to_update = "@60" END

COPY_EXISTING ~wmart1.sto~ ~override~  // add item to Joluv shop

	LPF ADD_STORE_ITEM_EX
      STR_VAR item_name=~xohfbtsb~ flags=~identified~
    END
