//////////////////////////////
// 11 - Young Ned's Knucky //
////////////////////////////

COPY ~weidu_external/%MOD_FOLDER%/bam/iamul30.bam~ ~override~

COPY ~iwditempack/itm/xohfamlk.itm~ ~override~
	SAY NAME1 @62
	SAY UNIDENTIFIED_DESC @63
	SAY NAME2 @64
	LPF ~GW_WRITE_EE_ITM_DESCRIPTIONS~ STR_VAR GW_desc_to_update = "@65" END
	WRITE_ASCII 0x58 ~CAMUL02~ (8) // Description image

COPY_EXISTING ~wmart1.sto~ ~override~  // add item to Joluv shop

	LPF ADD_STORE_ITEM_EX
		STR_VAR item_name=~xohfamlk~ flags=~identified~
	END
